spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8888
signing-key: 771d02d0825052bb9100e8fa5cea671dd071271c1620d938f286fbbbbb50f213
token-expiration: 600_000